sudo: required

service:
  - docker

env:
  - CONTAINER_IMAGE_TAG=neuron:gcc-ompi

before_install:
  - docker build -t $CONTAINER_IMAGE_TAG neuron-gcc-ompi
  - docker run -d $CONTAINER_IMAGE_TAG

notifications:
  slack: microbrain:dHXYnMz4KBlHXHLs64ju5h5Y
